spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
  security:
    user:
      password: CONFIG_SERVICE_PASSWORD

  application:
    name: config-server


server:
  port: 8888