version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: springCloud
    volumes:
      - './initDB:/docker-entrypoint-initdb.d'
      - './data/db:/data/db'
      - './data/configdb:/data/configdb'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongodb:mongo
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: MONGODB_PASSWORD