spring:
  data:
    mongodb:
      host: localhost
      username: user
      password: MONGODB_PASSWORD
      database: springCloud
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000
