spring:
  data:
    mongodb:
      host: mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: springCloud
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/